\begin{tetris}[bsc_cis_physik]
	\drawsemester{1. Semester\\(WiSe 14/15)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung I}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Proseminar}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik I}
		\drawmodule{8}{tetris_red}{transparent}{black}{Physikalisches Praktikum I}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
	\drawsemester{2. Semester\\(SoSe 15)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung II}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Formale Grundlagen\\der Informatik I}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik II}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{3. Semester\\(WiSe 15/16)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Algorithmen und\\Datenstrukturen}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Grundlagen von\\Datenbanken}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Formale Grundl.\ d.\ Informatik II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{4. Semester\\(SoSe 16)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Programmierung für\\Naturwissenschaften}
		\drawmoduleincomplete{9}{tetris_red}{transparent}{black}{Theoretische Physik II}
		\drawmodule{6}{tetris_gray}{transparent}{black}{Stochastik}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{5. Semester\\(WiSe 16/17)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Hochleistungsrechnen}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Computational\\Physics}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Projekt\\CiS Physik}
        \drawmodule{7}{tetris_red}{transparent}{black}{Wahlpflicht 3\\Physik V\\(Kern- und Teilchenphysik)}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{6. Semester\\(SoSe 17)}
		\drawmodule{9}{tetris_red}{transparent}{black}{Theoretische Physik II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Seminar}
		\drawmodule{6}{white}{black}{black}{Zusätzlich\\Cluster Competition}
	\drawsemester{7. Semester\\(WiSe 17/18)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Rechnerstrukturen}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Mathematik III für Physiker}
		\drawmodule{7.5}{white}{black}{black}{HiWi\\DKRZ 10h}
	\drawsemester{8. Semester\\(SoSe 18)}
		\drawmodule{12}{tetris_yellow}{transparent}{black}{Abschlussmodul\\(Bachelorarbeit)}
		\drawmodule{6}{white}{black}{black}{Zusätzlich\\Cluster Competition}
		\drawmodule{15}{white}{black}{black}{HiWi\\DKRZ 20h}
    \drawsemester{1. (9.) Semester\\(WiSe 18/19)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik\\Computer Vision I}
		\drawmoduleincomplete{9}{tetris_blue}{transparent}{black}{Wahlpflicht Theorie\\Kryptographie}
		\drawmoduleincomplete{12}{tetris_blue}{transparent}{black}{Projekt\\Paralleles Rechnen\\für Fortgeschrittene}
    \drawsemester{2. (10.) Semester\\(SoSe 19)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik\\Hochleistungs-Ein-/Ausgabe}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Vertiefung\\Informatik\\Neuronale Netze}
		\drawmodule{6}{white}{black}{black}{Freier\\Wahlbereich\\Astronomie und\\Astrophysik I}
    \drawsemester{3. (11.) Semester\\(WiSe 19/20)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht\\Algorithmik}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Wahlpflicht\\Maschinelles Lernen}
		\drawmodule{6}{white}{black}{black}{Freier\\Wahlbereich\\Astronomie und\\Astrophysik II}
		\drawmodule{9}{white}{black}{black}{Freier\\Wahlbereich\\Algebra}
		\drawmodule{9}{white}{black}{black}{Freier\\Wahlbereich\\Theoretische Physik I}
        \drawmodule{3}{white}{black}{black}{Freier\\Wahlbereich\\Seminar: Moderne Themen\\aus der Astrophysik}
   % \drawsemester{1. (12.) Semester\\(SoSe 20)}
    \drawsemester{Skala (30 lp)}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
\end{tetris}
