\begin{tetris}[bsc_cis_physik]
	\drawsemester{1. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung I}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Proseminar}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik I}
		\drawmodule{8}{tetris_red}{transparent}{black}{Physikalisches Praktikum I}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
	\drawsemester{2. Semester\\(SoSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Softwareentwicklung II}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Formale Grundlagen\\der Informatik I}
		\drawmodule{12}{tetris_red}{transparent}{black}{Physik II}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{3. Semester\\(WiSe)}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Algorithmen und\\Datenstrukturen}
		\drawmodule{6}{tetris_blue}{transparent}{black}{Grundlagen von\\Datenbanken}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Formale Grundl.\ d.\ Informatik II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik I für Physiker}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{4. Semester\\(SoSe)}
		\drawmodule{9}{tetris_blue}{transparent}{black}{Programmierung für\\Naturwissenschaften}
		\drawmoduleincomplete{9}{tetris_red}{transparent}{black}{Theoretische Physik II}
		\drawmodule{6}{tetris_gray}{transparent}{black}{Stochastik}
		\drawmoduleincomplete{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
	\drawsemester{5. Semester\\(WiSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Hochleistungsrechnen}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Computational\\Physics}
		\drawmodule{6}{tetris_yellow}{transparent}{black}{Projekt\\CiS Physik}
        \drawmodule{7}{tetris_red}{transparent}{black}{Wahlpflicht 3\\Physik V\\(Kern- und Teilchenphysik)}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Numerische Mathematik}
	\drawsemester{6. Semester\\(SoSe)}
		\drawmodule{9}{tetris_red}{transparent}{black}{Theoretische Physik II}
		\drawmodule{9}{tetris_gray}{transparent}{black}{Mathematik II für Physiker}
		\drawmodule{3}{tetris_yellow}{transparent}{black}{CiS-\\Seminar}
		\drawmodule{6}{white}{black}{black}{Zusätzlich\\Cluster Competition}
	\drawsemester{7. Semester\\(WiSe)}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 2\\Rechnerstrukturen}
		\drawmodule{9}{white}{black}{black}{Wahlpflicht 1\\Mathematik III für Physiker}
		\drawmodule{7.5}{white}{black}{black}{HiWi\\DKRZ 10h}
	\drawsemester{8. Semester\\(SoSe)}
		\drawmodule{12}{tetris_yellow}{transparent}{black}{Abschlussmodul\\(Bachelorarbeit)}
		\drawmodule{6}{white}{black}{black}{Zusätzlich\\Cluster Competition}
		\drawmodule{15}{white}{black}{black}{HiWi\\DKRZ 20h}
        \drawsemester{Skala (30 lp)}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
		\drawmodule{3}{white}{black}{black}{3 lp}
\end{tetris}
